### ISSUE TITLE
Docker Compose File

### ISSUE THREAD

**Issue by Balok-Fesarius** [citruz/fakeartist#15]
Can you provide a sample Docker Compose file for your docker image?

**Comment by citruz** [comment]
Sure. What are you trying to do? Run the game locally?

**Comment by Balok-Fesarius** [comment]
Yup.  When I tried to run the container I got missing secret key base errors.  ¯\_(ツ)_/¯ It would help if you could provide a working compose file for me to look at.  thanks.

**Comment by citruz** [comment]
Yes you need to set `SECRET_KEY_BASE` to some random value. It is used to generate the cookies.
If want to expose the app on a domain different than localhost you need to set `EXT_PORT` and `EXT_HOST` accordingly.

This is the docker compose file that I use (you can ignore the traefik part):
```
services:
  fakeartist:
    image: citruz/fakeartist:latest
    container_name: fakeartist
    networks:
      - proxy
    restart: always
    environment:
       - EXT_PORT=443
       - EXT_HOST=fakeartist.felixseele.de
       - SECRET_KEY_BASE=SOME_RANDOM_VALUE
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.fakeartist-secure.entrypoints=websecure"
      - "traefik.http.routers.fakeartist-secure.rule=Host(`fakeartist.felixseele.de`)"
      - "traefik.http.routers.fakeartist-secure.service=fakeartist-service"
      - "traefik.http.services.fakeartist-service.loadbalancer.server.port=4000"

networks:
  proxy:
    external: true

```
